### ISSUE TITLE
No open button for this lesson

### ISSUE THREAD

**Issue by stevenchu** [learn-co-curriculum/js-what-is-a-test#10]
There's no open button for this lesson, but it uses language like "First things first, open up index.js in your terminal", which confuses students. 

"This should look familiar except for that third line: var message = `${name} is ${height} inches tall`"

Our index.js doesn't say that, so this copy should be revised

**Comment by maxwellbenton** [comment]
Hi @stevenchu, 

Thank you for reporting this. This issue was due to Learn misinterpreting this lesson. We've updated this lesson and confirmed that it will now and recognize this as a lab, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
