### ISSUE TITLE
This section should be set up as a lesson, not a lab

### ISSUE THREAD

**Issue by courtneymorgan** [learn-co-curriculum/js-what-is-a-test#11]
I am not able to access any material for this lab in Learn IDE because there is no blue Open button at the top of the page
![screen shot 2017-07-07 at 11 53 03 am](https://user-images.githubusercontent.com/29407254/27965790-e1c11fb4-630a-11e7-87c4-472726cc1c5d.png)

**Comment by maxwellbenton** [comment]
Hi @courtneymorgan,
 
Thank you for reporting this. This issue was due to Learn misinterpreting this lesson. We've updated this lesson and confirmed that it will now and recognize this as a lab and that the `Open IDE` button now appears, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
