### ISSUE TITLE
suggested curriculum edit: nodejs

### ISSUE THREAD

**Issue by abarrdev** [learn-co-curriculum/js-what-is-a-test#25]
Hey!

In the previous lessons of Bootcamp Prep v2, I noticed I was being taught to run code in the terminal by typing out something like:
node index.js
Then, in later lessons and without explanation, that instruction changed to something like:
nodejs index.js

After Googling around a bit, I believe I understand that node is a pre-programmed alias for nodejs in the IDE. I hope I'm correct, but I think this deserves some explanation when this part of the instruction comes up.

Thanks!!

**Comment by maxwellbenton** [comment]
Hi @andreabarr87,

Thank you for providing this feedback. We've updated references to `nodejs` in our lesson contents so that they only say `node`. `nodejs` was an alias for the `node` command, but is deprecated and no longer works.

Thank you for taking the time to let us know about this and for helping to improve our curriculum!
