### ISSUE TITLE
my output

### ISSUE THREAD

**Issue by rbhogans** [learn-co-curriculum/js-what-is-a-test#28]
is totally different

**Comment by lizbur10** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
