### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Tokuhisa1** [learn-co-curriculum/js-what-is-a-test#4]
The README references a non-existent(?) index.js file.

**Comment by scarsam** [comment]
+1 Don't see the Open for Learn IDE for this assignment.

**Comment by maxwellbenton** [comment]
Hi @Tokuhisa1,

Thank you for reporting this. This issue was due to Learn misinterpreting this lesson. We've updated this lesson and confirmed that it will now display the included `index.js` file and recognize this as a lab.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.
