### ISSUE TITLE
Issue with "What is a Test"

### ISSUE THREAD

**Issue by dcraig11221** [learn-co-curriculum/js-what-is-a-test#9]
It seems there should be a lab associated with this lesson, but I see no button to open a lab. We are instructed to open up index.js and are shown what to expect to see. If I open up index.js from the previous lesson (node-practice-lab), I see some elements, but not what is shown. In addition there is no index-test.js file associated with the previous lab. Is there a link/button missing for a lab on this lesson? In fact, it seems the lab that is associated with the next lesson should be presented in this lesson.

**Comment by Jdev05** [comment]
There is for sure a missing open link but I managed to figure out a workaround for this issue. Open the github icon on this lab (or just click the Code tab on this page) and then click the green clone or download button. Copy the https link. Next go into the learn IDE and change your directory to the labs folder. If you just finished the previous lab just type "cd .." and that should do it. Next in the terminal part of the IDE type in: "git clone " and the link you copied from github.

**Comment by maxwellbenton** [comment]
Hi @dcraig11221, 

Thank you for reporting this. This issue was due to Learn misinterpreting this lesson. We've updated this lesson and confirmed that it will now recognize this as a lab and the `Open IDE` button will appear in Learn, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.
